from django.urls import path
from . import views

app_name = 'main'
urlpatterns = [
    path('cars/', views.cars_list, name='cars-list'),
    path('add-car/', views.add_car, name='add-car'),
    path('update-car/<int:pk>/', views.update_car, name='update-car'),
    path('delete-car/<int:pk>/', views.CarDeleteView.as_view(), name='delete-car'),
    path('reminders/', views.reminders_list, name='reminders-list'),
    path('add-reminder/', views.add_reminder, name='add-reminder'),
    path('update-reminder/<int:pk>/',
         views.update_reminder, name='update-reminder'),
    path('delete-reminder/<int:pk>/',
         views.ReminderDeleteView.as_view(), name='delete-reminder'),
    path('services/', views.services_list, name='services-list'),
    path('add-service/', views.add_service, name='add-service'),
    path('update-service/<int:pk>/', views.update_service, name='update-service'),
    path('delete-service/<int:pk>/',
         views.ServiceDeleteView.as_view(), name='delete-service'),
    path('users-details/', views.users_details_list, name='users-details-list'),
    path('set-unactive-user/<int:pk>/',
         views.user_set_unactive, name='user-set-unactive'),
    path('contractors/', views.contractors_list, name='contractors-list'),
    path('add-contractor/', views.add_contractor, name='add-contractor'),
    path('update-contractor/<int:pk>/',
         views.update_contractor, name='update-contractor'),
    path('delete-contractor/<int:pk>/',
         views.ContractorDeleteView.as_view(), name='delete-contractor'),
    path('', views.courses_list, name='courses-list'),
    path('add-course/', views.add_course, name='add-course'),
    path('update-course/<int:pk>/',
         views.update_course, name='update-course'),
    path('delete-course/<int:pk>/',
         views.CourseDeleteView.as_view(), name='delete-course'),
    path('course/<int:pk>/', views.course_information, name='course-information'),
    path('course/<int:pk>/add-expense/',
         views.add_expense, name='add-expense'),
    path('course/update-expense/<int:pk>/',
         views.update_expense, name='update-expense'),
    path('course/<int:course_pk>/delete-expense/<int:pk>/',
         views.ExpenseDeleteView.as_view(), name='delete-expense'),
    path('addresses/', views.addresses_list, name='addresses-list'),
    path('add-address/', views.add_address, name='add-address'),
    path('update-address/<int:pk>/',
         views.update_address, name='update-address'),
    path('delete-address/<int:pk>/',
         views.AddressDeleteView.as_view(), name='delete-address'),
    path('add-trip-order/', views.add_trip_order, name='add-trip-order'),
    path('load/course-options/', views.load_course_options,
         name='load-course-options'),
    path('load/dates/', views.load_dates,
         name='load-dates')
]
