# Generated by Django 2.2.24 on 2021-11-28 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='adr_expiration',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='digital_card_expiration',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='drivers_license_expiration',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='id_card_expiration',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='pasport_expiration',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='professional_competence',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='psychological_test_expiration',
            field=models.DateField(null=True),
        ),
    ]
