# Generated by Django 2.2.24 on 2021-12-05 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211128_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='adr_expiration',
            field=models.DateField(blank=True, null=True, verbose_name='Изтичане на ADR'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='digital_card_expiration',
            field=models.DateField(blank=True, null=True, verbose_name='Изтичане на дигитална карта'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='drivers_license_expiration',
            field=models.DateField(blank=True, null=True, verbose_name='Изтичане на шофьорска книжка'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id_card_expiration',
            field=models.DateField(blank=True, null=True, verbose_name='Изтичане на лична карта'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='pasport_expiration',
            field=models.DateField(blank=True, null=True, verbose_name='Изтичане на паспорт'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='professional_competence',
            field=models.DateField(blank=True, null=True, verbose_name='Изтичане на професионална компетентност'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='psychological_test_expiration',
            field=models.DateField(blank=True, null=True, verbose_name='Изтичане на психотест'),
        ),
    ]
