# Generated by Django 2.2.24 on 2022-01-27 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_courseinvoice_additional_information'),
        ('users', '0005_customuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Bank', verbose_name='Банка'),
        ),
    ]
