# Generated by Django 2.2.24 on 2022-01-30 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customuser_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='personal_id',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='ЕГН'),
        ),
    ]
