# Generated by Django 2.2.27 on 2022-04-08 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20220320_0257'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['first_name', 'middle_name', 'last_name'], 'verbose_name': 'Потребител', 'verbose_name_plural': 'Потребители'},
        ),
    ]
