# Generated by Django 2.2.27 on 2022-04-14 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_documenttype_userdocument'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documenttype',
            options={'ordering': ['document_type'], 'verbose_name': 'Тип документ', 'verbose_name_plural': 'Типове документи'},
        ),
    ]
