# Generated by Django 2.2.27 on 2022-04-14 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20220414_1953'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdocument',
            options={'verbose_name': 'Документ на потребител', 'verbose_name_plural': 'Документи на потребители'},
        ),
    ]
