# Generated by Django 2.2.24 on 2021-11-15 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211114_1301'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReminderType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiration_date', models.DateField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Car')),
                ('reminder_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ReminderType')),
            ],
        ),
    ]
