# Generated by Django 2.2.24 on 2021-12-06 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_contractors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_type', models.CharField(choices=[('', 'Избери'), ('Български', 'Български'), ('Чуждестранен', 'Чуждестранен')], max_length=100, verbose_name='Тип клиент')),
                ('bulstat', models.CharField(max_length=100, verbose_name='Булстат')),
                ('city', models.CharField(max_length=100, verbose_name='Град')),
                ('name', models.CharField(max_length=100, verbose_name='Име')),
                ('mol', models.CharField(max_length=100, verbose_name='МОЛ')),
                ('country', models.CharField(max_length=100, verbose_name='Държава')),
                ('address', models.CharField(max_length=100, verbose_name='Адрес')),
                ('phone_number', models.CharField(max_length=100, verbose_name='Телефонен номер')),
                ('email', models.CharField(max_length=100, verbose_name='E-mail')),
                ('charging_vat', models.CharField(choices=[('', 'Избери'), ('чл.21 ал.2 от ЗДДС', 'чл.21 ал.2 от ЗДДС'), ('чл. 30, ал.1 от ЗДДС', 'чл. 30, ал.1 от ЗДДС')], max_length=100, verbose_name='Основание за неначисление на ДДС')),
                ('cmr_photo', models.FileField(upload_to='cmr_photos', verbose_name='Прикачи ЧМР')),
                ('license_photo', models.FileField(upload_to='license_photos', verbose_name='Прикачи лиценз или друг документ')),
                ('expiration_date', models.DateField(verbose_name='Дата на изтичане')),
            ],
        ),
        migrations.DeleteModel(
            name='Contractors',
        ),
        migrations.AlterField(
            model_name='reminder',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Car', verbose_name='Автомобил'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='expiration_date',
            field=models.DateField(verbose_name='Дата на изтичнане'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='reminder_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ReminderType', verbose_name='Вид напомняне'),
        ),
        migrations.AlterField(
            model_name='remindertype',
            name='reminder_type',
            field=models.CharField(max_length=50, verbose_name='Вид напомняне'),
        ),
        migrations.AlterField(
            model_name='service',
            name='additional_information',
            field=models.CharField(max_length=500, verbose_name='Допълнителна информация'),
        ),
        migrations.AlterField(
            model_name='service',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Car', verbose_name='Автомобил'),
        ),
        migrations.AlterField(
            model_name='service',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='service',
            name='run',
            field=models.CharField(max_length=30, verbose_name='Пробег'),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_type',
            field=models.CharField(max_length=200, verbose_name='Вид обслужване'),
        ),
    ]
