# Generated by Django 2.2.24 on 2021-12-06 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20211207_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='expiration_date',
            field=models.DateField(blank=True, verbose_name='Дата на изтичане'),
        ),
    ]
