# Generated by Django 2.2.24 on 2021-12-06 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20211207_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='bulstat',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Булстат'),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='charging_vat',
            field=models.CharField(blank=True, choices=[('', 'Избери'), ('чл.21 ал.2 от ЗДДС', 'чл.21 ал.2 от ЗДДС'), ('чл. 30, ал.1 от ЗДДС', 'чл. 30, ал.1 от ЗДДС')], max_length=100, null=True, verbose_name='Основание за неначисление на ДДС'),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Град'),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='cmr_photo',
            field=models.FileField(blank=True, null=True, upload_to='cmr_photos', verbose_name='Прикачи ЧМР'),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Държава'),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='expiration_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата на изтичане'),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='license_photo',
            field=models.FileField(blank=True, null=True, upload_to='license_photos', verbose_name='Прикачи лиценз или друг документ'),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='mol',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='МОЛ'),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='phone_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Телефонен номер'),
        ),
    ]
