# Generated by Django 2.2.24 on 2021-12-07 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20211207_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='additional_information',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Допълнителна информация'),
        ),
    ]
