# Generated by Django 2.2.24 on 2021-12-12 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20211207_0216'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='maturity_date',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Дата на падеж'),
        ),
    ]
