# Generated by Django 2.2.24 on 2021-12-14 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_contractor_maturity_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_type', models.CharField(max_length=50, verbose_name='Вид автомобил')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(max_length=100, verbose_name='Вид обслужване')),
            ],
        ),
        migrations.AlterField(
            model_name='reminder',
            name='reminder_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.ReminderType', verbose_name='Вид напомняне'),
        ),
        migrations.AlterField(
            model_name='service',
            name='run',
            field=models.CharField(max_length=20, verbose_name='Пробег'),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.ServiceType', verbose_name='Вид обслужване'),
        ),
        migrations.AddField(
            model_name='car',
            name='car_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.CarType', verbose_name='Вид автомобил'),
        ),
    ]
