# Generated by Django 2.2.24 on 2021-12-26 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_address_course_courseaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseaddress',
            name='loаding_type',
        ),
        migrations.AddField(
            model_name='courseaddress',
            name='load_type',
            field=models.CharField(choices=[('', 'Избери'), ('loading_address', 'Адрес на товарене'), ('unloading_address', 'Адрес на разтоварване')], default='asd', max_length=30, verbose_name='Вид на товарене'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='contact_person',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Лице за контакт'),
        ),
        migrations.AlterField(
            model_name='address',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Телефон за връзка'),
        ),
        migrations.AlterField(
            model_name='address',
            name='gps_coordinats',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='GPS координати'),
        ),
        migrations.AlterField(
            model_name='course',
            name='currency',
            field=models.CharField(choices=[('', 'Избери'), ('BGN', 'BGN'), ('EUR', 'EUR'), ('USD', 'USD'), ('GBP', 'GBP'), ('CAD', 'CAD')], max_length=5, verbose_name='Валута'),
        ),
    ]
