# Generated by Django 2.2.24 on 2021-12-27 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20211227_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseaddress',
            name='address',
        ),
        migrations.AddField(
            model_name='courseaddress',
            name='address_input',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Въведен адрес'),
        ),
        migrations.AddField(
            model_name='courseaddress',
            name='address_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Address', verbose_name='Свързан адрес'),
        ),
    ]
