# Generated by Django 2.2.24 on 2021-12-30 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20211227_1708'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='gps_coordinats',
            new_name='gps_coordinates',
        ),
    ]
