# Generated by Django 2.2.24 on 2022-01-01 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_expense_expensetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseaddress',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='expense_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ExpenseType', verbose_name='Вид разход'),
        ),
    ]
