# Generated by Django 2.2.24 on 2022-01-05 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20220101_1900'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='user',
            new_name='driver',
        ),
    ]
