# Generated by Django 2.2.24 on 2022-01-07 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0022_auto_20220106_0024'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=100, verbose_name='Дестинация')),
                ('from_date', models.DateField(verbose_name='Начална дата')),
                ('to_date', models.DateField(verbose_name='Крайна дата')),
                ('creation_date', models.DateField(auto_now_add=True, verbose_name='Дата на създаване')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Course', verbose_name='Курс')),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Шофьор')),
            ],
        ),
    ]
