# Generated by Django 2.2.24 on 2022-01-09 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_expenseorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenseorder',
            name='BGN_amount',
            field=models.FloatField(blank=True, null=True, verbose_name='Сума в лева'),
        ),
        migrations.AlterField(
            model_name='expenseorder',
            name='EUR_amount',
            field=models.FloatField(blank=True, null=True, verbose_name='Сума в евро'),
        ),
    ]
