# Generated by Django 2.2.24 on 2022-01-20 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20220109_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='correspondence_address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Адрес за кореспонденция'),
        ),
    ]
