# Generated by Django 2.2.24 on 2022-01-21 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20220109_2046'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('', 'Избери'), ('Кеш', 'Кеш'), ('Дебитна карта', 'Дебитна карта'), ('Кредитна карта', 'Кредитна карта'), ('Банков превод', 'Банков превод')], max_length=50, verbose_name='Вид плащане')),
                ('measure_type', models.CharField(choices=[('', 'Избери'), ('Тон', 'Тон'), ('Курс', 'Курс'), ('Брой', 'Брой'), ('Километър', 'Километър')], max_length=15, verbose_name='Мярка')),
                ('invoice_type', models.CharField(choices=[('', 'Избери'), ('Фактура', 'Фактура'), ('Кредитно известие', 'Кредитно известие'), ('Дебитно известие', 'Дебитно известие')], max_length=30, verbose_name='Вид документ')),
                ('tax_type', models.CharField(choices=[('Стандартна фактура', 'Стандартна фактура'), ('Фактура без начисление на ДДС', 'Фактура без начисление на ДДС')], max_length=30, verbose_name='ДДС')),
                ('quantity', models.IntegerField(verbose_name='Количество')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Course', verbose_name='Курс')),
            ],
        ),
    ]
