# Generated by Django 2.2.24 on 2022-01-22 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_contractor_correspondence_address'),
        ('main', '0026_courseinvoice'),
    ]

    operations = [
    ]
