# Generated by Django 2.2.24 on 2022-01-22 12:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_merge_20220122_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseinvoice',
            name='creation_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата на създаване'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='courseinvoice',
            name='tax_type',
            field=models.CharField(choices=[('', 'Избери'), ('Стандартна фактура', 'Стандартна фактура'), ('Фактура без начисление на ДДС', 'Фактура без начисление на ДДС')], max_length=30, verbose_name='ДДС'),
        ),
    ]
