# Generated by Django 2.2.24 on 2022-01-24 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_auto_20220122_1402'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Име')),
                ('bulstat', models.CharField(blank=True, max_length=100, null=True, verbose_name='Булстат')),
                ('mol', models.CharField(blank=True, max_length=100, null=True, verbose_name='МОЛ')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Град')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Адрес')),
                ('correspondence_address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Адрес за кореспонденция')),
                ('phone_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Телефонен номер')),
            ],
        ),
    ]
