# Generated by Django 2.2.24 on 2022-01-25 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='branch_name',
            field=models.CharField(default='asd', max_length=50, verbose_name='Банков клон'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bank',
            name='iban',
            field=models.CharField(default='123123', max_length=50, verbose_name='IBAN'),
            preserve_default=False,
        ),
    ]
