# Generated by Django 2.2.24 on 2022-01-25 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_auto_20220125_2025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='branch_name',
        ),
        migrations.AddField(
            model_name='bank',
            name='bank_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Банков код'),
        ),
    ]
