# Generated by Django 2.2.24 on 2022-01-26 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_course_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='contact_person',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Лице за контакт'),
        ),
    ]
