# Generated by Django 2.2.24 on 2022-01-26 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_courseinvoice_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='request_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер на заявка'),
        ),
    ]
