# Generated by Django 2.2.24 on 2022-01-26 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_courseinvoice_tax_transaction_basis'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseinvoice',
            name='additional_information',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Допълнителна информация'),
        ),
    ]
