# Generated by Django 2.2.24 on 2022-01-28 00:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0040_expenseorder_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='triporder',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator', to=settings.AUTH_USER_MODEL, verbose_name='Създател'),
        ),
        migrations.AlterField(
            model_name='triporder',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver', to=settings.AUTH_USER_MODEL, verbose_name='Шофьор'),
        ),
    ]
