# Generated by Django 2.2.24 on 2022-01-30 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0043_auto_20220129_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triporder',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triporder_creator', to=settings.AUTH_USER_MODEL, verbose_name='Създател'),
        ),
        migrations.AlterField(
            model_name='triporder',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triporder_driver', to=settings.AUTH_USER_MODEL, verbose_name='Шофьор'),
        ),
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Град')),
                ('creation_date', models.DateField(auto_now_add=True, verbose_name='Дата на създаване')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Company', verbose_name='Фирма')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instruction_creator', to=settings.AUTH_USER_MODEL, verbose_name='Създател')),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instruction_driver', to=settings.AUTH_USER_MODEL, verbose_name='Шофьор')),
            ],
        ),
    ]
