# Generated by Django 2.2.24 on 2022-01-30 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_instruction_car'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Course', verbose_name='Курс')),
            ],
        ),
        migrations.CreateModel(
            name='CourseMedicalExmaination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Course', verbose_name='Курс')),
            ],
        ),
    ]
