# Generated by Django 2.2.24 on 2022-01-30 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_coursemedicalexmaination_courseservice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='create_date',
            new_name='creation_date',
        ),
        migrations.AlterField(
            model_name='courseservice',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_service', to='main.Course', verbose_name='Курс'),
        ),
    ]
