# Generated by Django 2.2.24 on 2022-01-30 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_auto_20220131_0123'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourseMedicalExmaination',
            new_name='CourseMedicalExamination',
        ),
    ]
