# Generated by Django 2.2.24 on 2022-01-31 16:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_auto_20220131_0137'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemedicalexamination',
            name='creation_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата на създаване'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courseservice',
            name='creation_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата на създаване'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coursemedicalexamination',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_medical_examination', to='main.Course', verbose_name='Курс'),
        ),
    ]
