# Generated by Django 2.2.24 on 2022-01-31 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_auto_20220131_1817'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourseService',
            new_name='CourseServiceExamination',
        ),
    ]
