# Generated by Django 2.2.24 on 2022-02-01 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0050_auto_20220131_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemedicalexamination',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_medical_examination', to='main.Course', verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='courseserviceexamination',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_service', to='main.Course', verbose_name='Курс'),
        ),
    ]
