# Generated by Django 2.2.24 on 2022-02-01 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0051_auto_20220201_0255'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Пощенски код'),
        ),
    ]
