# Generated by Django 2.2.24 on 2022-02-01 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0052_contractor_postal_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemedicalexamination',
            name='perpetrator',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Извършител'),
        ),
        migrations.AddField(
            model_name='courseserviceexamination',
            name='perpetrator',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Извършител'),
        ),
    ]
