# Generated by Django 2.2.24 on 2022-02-02 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0054_auto_20220202_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.CarType', verbose_name='Вид автомобил'),
        ),
        migrations.AlterField(
            model_name='courseinvoice',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Course', verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='expenseorder',
            name='trip_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.TripOrder', verbose_name='Командировъчна заповед'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='reminder_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.ReminderType', verbose_name='Вид напомняне'),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.ServiceType', verbose_name='Вид обслужване'),
        ),
        migrations.AlterField(
            model_name='triporder',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Course', verbose_name='Курс'),
        ),
    ]
