# Generated by Django 2.2.24 on 2022-02-05 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0055_auto_20220202_1924'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Адрес', 'verbose_name_plural': 'Адреси'},
        ),
        migrations.AlterModelOptions(
            name='bank',
            options={'verbose_name': 'Банка', 'verbose_name_plural': 'Банки'},
        ),
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name': 'Автомобил', 'verbose_name_plural': 'Автомобили'},
        ),
        migrations.AlterModelOptions(
            name='cartype',
            options={'verbose_name': 'Вид автомобил', 'verbose_name_plural': 'Видове автомобили'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Компания', 'verbose_name_plural': 'Комапнии'},
        ),
        migrations.AlterModelOptions(
            name='contractor',
            options={'verbose_name': 'Контрагент', 'verbose_name_plural': 'Контрагенти'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Курс', 'verbose_name_plural': 'Курсове'},
        ),
        migrations.AlterModelOptions(
            name='courseaddress',
            options={'verbose_name': 'Адрес към курс', 'verbose_name_plural': 'Адреси към курсове'},
        ),
        migrations.AlterModelOptions(
            name='courseinvoice',
            options={'verbose_name': 'Технически преглед', 'verbose_name_plural': 'Технически прегледи'},
        ),
        migrations.AlterModelOptions(
            name='coursemedicalexamination',
            options={'verbose_name': 'Медицински преглед', 'verbose_name_plural': 'Медицински прегледи'},
        ),
        migrations.AlterModelOptions(
            name='courseserviceexamination',
            options={'verbose_name': 'Технически преглед', 'verbose_name_plural': 'Технически прегледи'},
        ),
        migrations.AlterModelOptions(
            name='expense',
            options={'verbose_name': 'Разход към курс', 'verbose_name_plural': 'Разходи към курсове'},
        ),
        migrations.AlterModelOptions(
            name='expenseorder',
            options={'verbose_name': 'Разходен ордер', 'verbose_name_plural': 'Разходни ордери'},
        ),
        migrations.AlterModelOptions(
            name='expensetype',
            options={'verbose_name': 'Вид разход', 'verbose_name_plural': 'Видове разходи'},
        ),
        migrations.AlterModelOptions(
            name='instruction',
            options={'verbose_name': 'Инструкция', 'verbose_name_plural': 'Инструкции'},
        ),
        migrations.AlterModelOptions(
            name='reminder',
            options={'verbose_name': 'Напомняне', 'verbose_name_plural': 'Напомняния'},
        ),
        migrations.AlterModelOptions(
            name='remindertype',
            options={'verbose_name': 'Вид напомняне', 'verbose_name_plural': 'Видове напомняния'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Техническо обслужване', 'verbose_name_plural': 'Технически обслужвания'},
        ),
        migrations.AlterModelOptions(
            name='servicetype',
            options={'verbose_name': 'Вид техническо обслужване', 'verbose_name_plural': 'Видове технически обслужвания'},
        ),
        migrations.AlterModelOptions(
            name='taxtransactionbasis',
            options={'verbose_name': 'Основание на сделка', 'verbose_name_plural': 'Основание на сделка'},
        ),
        migrations.AlterModelOptions(
            name='triporder',
            options={'verbose_name': 'Командировъчна заповед', 'verbose_name_plural': 'Командировъчни заповеди'},
        ),
        migrations.AddField(
            model_name='company',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='company',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Пощенски код'),
        ),
        migrations.AlterField(
            model_name='expenseorder',
            name='trip_order',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense_order', to='main.TripOrder', verbose_name='Командировъчна заповед'),
        ),
        migrations.AlterField(
            model_name='triporder',
            name='course',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trip_order', to='main.Course', verbose_name='Курс'),
        ),
    ]
