# Generated by Django 2.2.24 on 2022-02-05 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0056_auto_20220205_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='province',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Област'),
        ),
    ]
