# Generated by Django 2.2.27 on 2022-02-14 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0057_company_province'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseTechnicalInspection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perpetrator', models.CharField(blank=True, max_length=100, null=True, verbose_name='Извършител')),
                ('creation_date', models.DateField(auto_now_add=True, verbose_name='Дата на създаване')),
                ('course', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='technical_inspection', to='main.Course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Технически преглед',
                'verbose_name_plural': 'Технически прегледи',
            },
        ),
        migrations.DeleteModel(
            name='CourseServiceExamination',
        ),
    ]
