# Generated by Django 2.2.24 on 2022-02-15 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0059_auto_20220214_1909'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalExaminationPerpetrator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perpetrator', models.CharField(max_length=100, verbose_name='Извършител')),
            ],
            options={
                'verbose_name': 'Извършител на медицински преглед',
                'verbose_name_plural': 'Извършители на медицински прегледи',
            },
        ),
        migrations.CreateModel(
            name='TechnicalInspectionPerpetrator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perpetrator', models.CharField(max_length=100, verbose_name='Извършител')),
            ],
            options={
                'verbose_name': 'Извършител на технически преглед',
                'verbose_name_plural': 'Извършители на технически прегледи',
            },
        ),
        migrations.AlterField(
            model_name='coursemedicalexamination',
            name='course',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_examination', to='main.Course', verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='coursemedicalexamination',
            name='perpetrator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.MedicalExaminationPerpetrator', verbose_name='Извършител'),
        ),
        migrations.AlterField(
            model_name='coursetechnicalinspection',
            name='course',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='technical_inspection', to='main.Course', verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='coursetechnicalinspection',
            name='perpetrator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.TechnicalInspectionPerpetrator', verbose_name='Извършител'),
        ),
    ]
