# Generated by Django 2.2.24 on 2022-02-17 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0060_auto_20220215_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='price',
        ),
        migrations.AddField(
            model_name='course',
            name='course_price',
            field=models.FloatField(default=1000, verbose_name='Цена за курс'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='driver_salary',
            field=models.FloatField(default=1000, verbose_name='Цена за командировка'),
            preserve_default=False,
        ),
    ]
