# Generated by Django 2.2.24 on 2022-02-17 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0061_auto_20220217_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseaddress',
            name='load_type',
            field=models.CharField(choices=[('', 'Избери'), ('Адрес на товарене', 'Адрес на товарене'), ('Адрес на разтоварване', 'Адрес на разтоварване'), ('Адрес на митница', 'Адрес на митница')], max_length=30, verbose_name='Товарен/Разтоварен/Митница'),
        ),
    ]
