# Generated by Django 2.2.24 on 2022-02-17 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0063_address_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='mileage',
            field=models.IntegerField(default=1333, verbose_name='Километраж'),
            preserve_default=False,
        ),
    ]
