# Generated by Django 2.2.24 on 2022-02-17 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0064_course_mileage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='triporder',
            name='course',
        ),
        migrations.AddField(
            model_name='triporder',
            name='course_export',
            field=models.OneToOneField(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='trip_order_export', to='main.Course', verbose_name='Курс за износ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='triporder',
            name='course_import',
            field=models.OneToOneField(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='trip_order_import', to='main.Course', verbose_name='Курс за внос'),
            preserve_default=False,
        ),
    ]
