# Generated by Django 2.2.24 on 2022-02-19 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0065_auto_20220218_0129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contractor',
            old_name='expiration_date',
            new_name='cmr_expiration_date',
        ),
        migrations.AddField(
            model_name='contractor',
            name='license_expiration_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата на изтичане'),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='cmr_photo',
            field=models.FileField(blank=True, null=True, upload_to='cmr_photos', verbose_name='Прикачи ЧМР Застраховка'),
        ),
    ]
