# Generated by Django 2.2.27 on 2022-02-20 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0066_auto_20220219_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseaddress',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='main.Course', verbose_name='Курс'),
        ),
    ]
