# Generated by Django 2.2.27 on 2022-03-14 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0067_auto_20220220_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='course_invoice_id',
            field=models.IntegerField(default=1, verbose_name='Фактура №'),
        ),
        migrations.AddField(
            model_name='company',
            name='course_medical_examination_id',
            field=models.IntegerField(default=1, verbose_name='Медицински преглед към курс №'),
        ),
        migrations.AddField(
            model_name='company',
            name='course_technical_inspection_id',
            field=models.IntegerField(default=1, verbose_name='Технически преглед към курс №'),
        ),
        migrations.AddField(
            model_name='company',
            name='expense_order_id',
            field=models.IntegerField(default=1, verbose_name='Разходен Ордер №'),
        ),
        migrations.AddField(
            model_name='company',
            name='instruction_id',
            field=models.IntegerField(default=1, verbose_name='Инструкция №'),
        ),
        migrations.AddField(
            model_name='company',
            name='trip_order_id',
            field=models.IntegerField(default=1, verbose_name='Командировъчна заповед №'),
        ),
    ]
