# Generated by Django 2.2.27 on 2022-03-14 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0069_triporder_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenseorder',
            name='number',
            field=models.IntegerField(default=1, verbose_name='№'),
            preserve_default=False,
        ),
    ]
