# Generated by Django 2.2.27 on 2022-03-14 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0070_expenseorder_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseinvoice',
            name='number',
            field=models.IntegerField(default=1, verbose_name='№'),
            preserve_default=False,
        ),
    ]
