# Generated by Django 2.2.27 on 2022-03-14 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0071_courseinvoice_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemedicalexamination',
            name='number',
            field=models.IntegerField(default=1, verbose_name='№'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coursetechnicalinspection',
            name='number',
            field=models.IntegerField(default=1, verbose_name='№'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instruction',
            name='number',
            field=models.IntegerField(default=1, verbose_name='№'),
            preserve_default=False,
        ),
    ]
