# Generated by Django 2.2.27 on 2022-03-20 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0072_auto_20220314_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenseorder',
            name='trip_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense_order', to='main.TripOrder', verbose_name='Командировъчна заповед'),
        ),
    ]
