# Generated by Django 2.2.27 on 2022-03-21 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0074_auto_20220320_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='course_id',
            field=models.IntegerField(default=1, verbose_name='Курс №'),
        ),
        migrations.AddField(
            model_name='course',
            name='number',
            field=models.IntegerField(default=1, verbose_name='№'),
            preserve_default=False,
        ),
    ]
