# Generated by Django 2.2.27 on 2022-03-22 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0075_auto_20220321_1509'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bank',
            options={'ordering': ['name'], 'verbose_name': 'Банка', 'verbose_name_plural': 'Банки'},
        ),
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['brand'], 'verbose_name': 'Автомобил', 'verbose_name_plural': 'Автомобили'},
        ),
        migrations.AlterModelOptions(
            name='cartype',
            options={'ordering': ['car_type'], 'verbose_name': 'Вид автомобил', 'verbose_name_plural': 'Видове автомобили'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['name'], 'verbose_name': 'Компания', 'verbose_name_plural': 'Комапнии'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-number'], 'verbose_name': 'Курс', 'verbose_name_plural': 'Курсове'},
        ),
        migrations.AlterModelOptions(
            name='courseinvoice',
            options={'ordering': ['-number'], 'verbose_name': 'Фактура за курс', 'verbose_name_plural': 'Фактури за курсове'},
        ),
        migrations.AlterModelOptions(
            name='coursemedicalexamination',
            options={'ordering': ['-number'], 'verbose_name': 'Медицински преглед', 'verbose_name_plural': 'Медицински прегледи'},
        ),
        migrations.AlterModelOptions(
            name='coursetechnicalinspection',
            options={'ordering': ['-number'], 'verbose_name': 'Технически преглед', 'verbose_name_plural': 'Технически прегледи'},
        ),
        migrations.AlterModelOptions(
            name='expenseorder',
            options={'ordering': ['-number'], 'verbose_name': 'Разходен ордер', 'verbose_name_plural': 'Разходни ордери'},
        ),
        migrations.AlterModelOptions(
            name='expensetype',
            options={'ordering': ['expense_type'], 'verbose_name': 'Вид разход', 'verbose_name_plural': 'Видове разходи'},
        ),
        migrations.AlterModelOptions(
            name='fromto',
            options={'ordering': ['from_to'], 'verbose_name': 'Релация', 'verbose_name_plural': 'Релации'},
        ),
        migrations.AlterModelOptions(
            name='instruction',
            options={'ordering': ['-number'], 'verbose_name': 'Инструкция', 'verbose_name_plural': 'Инструкции'},
        ),
        migrations.AlterModelOptions(
            name='medicalexaminationperpetrator',
            options={'ordering': ['perpetrator'], 'verbose_name': 'Извършител на медицински преглед', 'verbose_name_plural': 'Извършители на медицински прегледи'},
        ),
        migrations.AlterModelOptions(
            name='remindertype',
            options={'ordering': ['reminder_type'], 'verbose_name': 'Вид напомняне', 'verbose_name_plural': 'Видове напомняния'},
        ),
        migrations.AlterModelOptions(
            name='servicetype',
            options={'ordering': ['service_type'], 'verbose_name': 'Вид техническо обслужване', 'verbose_name_plural': 'Видове технически обслужвания'},
        ),
        migrations.AlterModelOptions(
            name='taxtransactionbasis',
            options={'ordering': ['name'], 'verbose_name': 'Основание на сделка', 'verbose_name_plural': 'Основание на сделка'},
        ),
        migrations.AlterModelOptions(
            name='technicalinspectionperpetrator',
            options={'ordering': ['perpetrator'], 'verbose_name': 'Извършител на технически преглед', 'verbose_name_plural': 'Извършители на технически прегледи'},
        ),
        migrations.AlterModelOptions(
            name='triporder',
            options={'ordering': ['-number'], 'verbose_name': 'Командировъчна заповед', 'verbose_name_plural': 'Командировъчни заповеди'},
        ),
    ]
