# Generated by Django 2.2.27 on 2022-03-23 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0076_auto_20220323_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='mileage',
            field=models.FloatField(verbose_name='Километраж'),
        ),
    ]
