# Generated by Django 2.2.27 on 2022-03-23 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0077_auto_20220323_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='vin',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер на рама'),
        ),
    ]
