# Generated by Django 2.2.27 on 2022-03-23 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0078_car_vin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='currency',
            new_name='course_price_currency',
        ),
        migrations.AddField(
            model_name='course',
            name='driver_salary_currency',
            field=models.CharField(choices=[('', 'Избери'), ('BGN', 'BGN'), ('EUR', 'EUR'), ('USD', 'USD'), ('GBP', 'GBP'), ('CAD', 'CAD')], default='BGN', max_length=5, verbose_name='Валута'),
            preserve_default=False,
        ),
    ]
