# Generated by Django 2.2.27 on 2022-03-26 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0079_auto_20220323_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='from_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.FromTo', verbose_name='Релация'),
        ),
    ]
