# Generated by Django 2.2.27 on 2022-04-08 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0079_auto_20220323_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='cargo_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Вид и тегло на товара'),
        ),
        migrations.AlterField(
            model_name='course',
            name='from_to',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Релация'),
        ),
    ]
