# Generated by Django 2.2.27 on 2022-04-07 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0081_auto_20220404_1445'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_number', models.CharField(max_length=100, verbose_name='Номер на заявка')),
            ],
            options={
                'verbose_name': 'Номер на заявка',
                'verbose_name_plural': 'Номера на заявки',
                'ordering': ['request_number'],
            },
        ),
    ]
