# Generated by Django 2.2.27 on 2022-04-07 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0083_auto_20220407_1747'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargoType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo_type', models.CharField(max_length=100, verbose_name='Вид и тегло на товара')),
            ],
            options={
                'verbose_name': 'Вид и тегло на товара',
                'verbose_name_plural': 'Видове и тегла на товари',
                'ordering': ['cargo_type'],
            },
        ),
        migrations.AlterField(
            model_name='course',
            name='cargo_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.CargoType', verbose_name='Вид и тегло на товара'),
        ),
    ]
