# Generated by Django 2.2.27 on 2022-04-08 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0080_auto_20220408_1600'),
        ('main', '0085_remove_contractor_charging_vat'),
    ]

    operations = [
    ]
