# Generated by Django 2.2.27 on 2022-04-08 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0086_merge_20220408_1623'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['address'], 'verbose_name': 'Адрес', 'verbose_name_plural': 'Адреси'},
        ),
        migrations.AlterModelOptions(
            name='contractor',
            options={'ordering': ['name'], 'verbose_name': 'Контрагент', 'verbose_name_plural': 'Контрагенти'},
        ),
        migrations.AlterField(
            model_name='course',
            name='cargo_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.CargoType', verbose_name='Вид и тегло на товара'),
        ),
        migrations.AlterField(
            model_name='course',
            name='from_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.FromTo', verbose_name='Релация'),
        ),
    ]
