# Generated by Django 2.2.27 on 2022-04-12 18:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0087_auto_20220408_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='maturity_date',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Падеж'),
        ),
        migrations.AlterField(
            model_name='fromto',
            name='from_to',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='\n    Невалиден формат! Използвайте следния формат: "{Дестинация} до {Дестинация}",\n    с празни места и думата "до" между дестинациите.\n    ', regex='^.+ {1}до{1} {1}.+$')], verbose_name='Релация'),
        ),
    ]
