# Generated by Django 2.2.27 on 2022-04-13 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0089_contactperson_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='contact_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.ContactPerson', verbose_name='Лице за контакт'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Description', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='course',
            name='request_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.RequestNumber', verbose_name='Номер на заявка'),
        ),
    ]
