# Generated by Django 2.2.27 on 2022-04-24 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0090_auto_20220413_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instruction',
            name='car',
        ),
        migrations.RemoveField(
            model_name='instruction',
            name='city',
        ),
        migrations.RemoveField(
            model_name='instruction',
            name='company',
        ),
        migrations.RemoveField(
            model_name='instruction',
            name='driver',
        ),
        migrations.AddField(
            model_name='instruction',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instruction_course', to='main.Course', verbose_name='Курс'),
        ),
    ]
