# Generated by Django 2.2.27 on 2022-04-24 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0091_auto_20220424_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instruction',
            name='course',
            field=models.ForeignKey(default='2', on_delete=django.db.models.deletion.CASCADE, related_name='instruction_course', to='main.Course', verbose_name='Курс'),
            preserve_default=False,
        ),
    ]
