# Generated by Django 2.2.27 on 2022-04-24 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0092_auto_20220424_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='course_files', verbose_name='Прикачи файл'),
        ),
    ]
