# Generated by Django 2.2.27 on 2022-04-30 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0094_auto_20220430_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triporder',
            name='from_date',
            field=models.DateField(blank=True, null=True, verbose_name='Начална дата'),
        ),
        migrations.AlterField(
            model_name='triporder',
            name='to_date',
            field=models.DateField(blank=True, null=True, verbose_name='Крайна дата'),
        ),
    ]
