# Generated by Django 2.2.27 on 2022-05-06 15:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0095_auto_20220430_1850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='driver',
        ),
        migrations.AddField(
            model_name='course',
            name='driver',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Шофьор'),
        ),
    ]
