# Generated by Django 2.2.27 on 2022-05-07 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0096_auto_20220506_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='instruction',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instruction_driver', to=settings.AUTH_USER_MODEL, verbose_name='Шофьор'),
        ),
    ]
