# Generated by Django 2.2.27 on 2022-05-07 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0099_coursetechnicalinspection_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemedicalexamination',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_examination', to='main.Course', verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='coursetechnicalinspection',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_inspection', to='main.Course', verbose_name='Курс'),
        ),
    ]
