# Generated by Django 2.2.27 on 2022-05-10 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0100_auto_20220508_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseinvoice',
            name='course',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Course', verbose_name='Курс'),
        ),
    ]
