# Generated by Django 2.2.27 on 2022-06-26 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0101_auto_20220510_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseinvoice',
            name='course',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='main.Course', verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='courseinvoice',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to=settings.AUTH_USER_MODEL, verbose_name='Създател'),
        ),
        migrations.AlterField(
            model_name='coursemedicalexamination',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_examinations', to='main.Course', verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='coursemedicalexamination',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_examinations', to=settings.AUTH_USER_MODEL, verbose_name='Шофьор'),
        ),
        migrations.AlterField(
            model_name='coursetechnicalinspection',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_inspections', to='main.Course', verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='coursetechnicalinspection',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technical_inspections', to=settings.AUTH_USER_MODEL, verbose_name='Шофьор'),
        ),
        migrations.AlterField(
            model_name='expenseorder',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_orders', to=settings.AUTH_USER_MODEL, verbose_name='Създател'),
        ),
        migrations.AlterField(
            model_name='expenseorder',
            name='trip_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense_orders', to='main.TripOrder', verbose_name='Командировъчна заповед'),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructions', to='main.Course', verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instructions_creator', to=settings.AUTH_USER_MODEL, verbose_name='Създател'),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instructions_driver', to=settings.AUTH_USER_MODEL, verbose_name='Шофьор'),
        ),
        migrations.AlterField(
            model_name='triporder',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_orders', to='main.Course', verbose_name='Курс за износ'),
        ),
        migrations.AlterField(
            model_name='triporder',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trip_orders_creator', to=settings.AUTH_USER_MODEL, verbose_name='Създател'),
        ),
        migrations.AlterField(
            model_name='triporder',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trip_orders_driver', to=settings.AUTH_USER_MODEL, verbose_name='Шофьор'),
        ),
    ]
