# Generated by Django 2.2.27 on 2022-06-26 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0102_auto_20220626_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='main.CarType', verbose_name='Вид автомобил'),
        ),
        migrations.AlterField(
            model_name='course',
            name='bank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='main.Bank', verbose_name='Банка'),
        ),
        migrations.AlterField(
            model_name='course',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='main.Car', verbose_name='Автомобил'),
        ),
        migrations.AlterField(
            model_name='course',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='main.Company', verbose_name='Фирма'),
        ),
        migrations.AlterField(
            model_name='course',
            name='driver',
            field=models.ManyToManyField(related_name='courses', to=settings.AUTH_USER_MODEL, verbose_name='Шофьор'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='main.Course', verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='expense_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='main.ExpenseType', verbose_name='Вид разход'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='reminder_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='main.ReminderType', verbose_name='Вид напомняне'),
        ),
        migrations.AlterField(
            model_name='service',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='main.Car', verbose_name='Автомобил'),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='main.ServiceType', verbose_name='Вид обслужване'),
        ),
    ]
